### ISSUE TITLE
Conflicting documentation - debugprobe on Pico 2

### ISSUE THREAD

**Issue by arc12** [raspberrypi/documentation#3880]
A This page - https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html#debugging-using-another-pico-series-device - states:
"Pico 2 is not yet supported by debuprobe_on_pico debugging software. "

B The getting started guide states :
"One Pico or Pico 2 can reprogram and debug another using the debugprobe firmware, which transforms the Pico or Pico 2
into a USB → SWD and UART bridge."

C. The README for this repo describes how to build debugprobe_on_pico for Pico 2.

Is "A" in need of revision?

**Comment by nathan-contino** [comment]
Fixed!

**Comment by Palantir555** [comment]
Does it take a while for the changes to be applied to the docs site? I'm still seeing the warning message on the website, which had me double-checking for a while. No biggie regardless, just letting you know in case it wasn't submitted.

**Comment by lurch** [comment]
> Does it take a while for the changes to be applied to the docs site?

Yes. The documentation has already been fixed on the [`develop` branch](https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/microcontrollers/pico-series/utilities.adoc) but it won't be visible at https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html#debugging-using-another-pico-series-device until @nathan-contino merges the `develop` branch into the [`master` branch](https://github.com/raspberrypi/documentation/blob/master/documentation/asciidoc/microcontrollers/pico-series/utilities.adoc) :slightly_smiling_face:
